'use strict';
/**
 * Deterministic generator for db/07_seed.sql.
 * Not part of the runtime app — a build-time tool. Uses a seeded PRNG
 * (not Math.random) so the output is byte-identical across runs, per
 * ARCHITECTURE.md §3.7 ("Generated, not random — the test plan
 * references specific IDs").
 *
 * Run: node db/seed_generator/generate_seed.js > db/07_seed.sql
 * (the npm script `npm run seed:generate` in server/ wraps this)
 */

const fs = require('fs');
const path = require('path');

// ---- seeded PRNG (mulberry32) for full determinism ----
function mulberry32(seed) {
  return function () {
    seed |= 0; seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rnd = mulberry32(20260220);
const pick = (arr) => arr[Math.floor(rnd() * arr.length)];
const pickWeighted = (arr) => pick(arr); // arr already pre-weighted by repetition
const randInt = (min, max) => Math.floor(rnd() * (max - min + 1)) + min;
const chance = (p) => rnd() < p;

function sqlStr(s) {
  if (s === null || s === undefined) return 'NULL';
  return "'" + String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
}
function sqlVal(v) {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return String(v);
  if (v instanceof Date) return "'" + v.toISOString().slice(0, 19).replace('T', ' ') + "'";
  return sqlStr(v);
}

const out = [];
const insertBatch = (table, columns, rows, comment) => {
  if (comment) out.push(`-- ${comment}`);
  if (rows.length === 0) return;
  out.push(`INSERT INTO ${table} (${columns.join(', ')}) VALUES`);
  const lines = rows.map(
    (r) => '  (' + columns.map((c) => sqlVal(r[c])).join(', ') + ')'
  );
  out.push(lines.join(',\n') + ';');
  out.push('');
};

out.push('-- =====================================================================');
out.push('-- 07_seed.sql');
out.push('-- Deterministic seed data (generated by db/seed_generator/generate_seed.js,');
out.push('-- fixed PRNG seed 20260220 — re-running the generator reproduces this file');
out.push('-- byte-for-byte). Volumes per ARCHITECTURE.md §3.7. Internally consistent:');
out.push('-- date ordering, resolution durations, unassigned equipment, expired/missing');
out.push('-- licences, overlapping specialist expertise, and one hierarchy branch with');
out.push('-- no specialist at the specific level (two branches, in fact — see');
out.push('-- specialist_expertise below) to exercise the fallback path.');
out.push('-- DO NOT EDIT BY HAND — edit the generator and regenerate.');
out.push('-- =====================================================================');
out.push('');
out.push('SET FOREIGN_KEY_CHECKS = 0;');
out.push('TRUNCATE TABLE audit_log;');
out.push('TRUNCATE TABLE call_log;');
out.push('TRUNCATE TABLE problem;');
out.push('TRUNCATE TABLE specialist_expertise;');
out.push('TRUNCATE TABLE helpdesk_staff;');
out.push('TRUNCATE TABLE problem_type;');
out.push('TRUNCATE TABLE software_licence;');
out.push('TRUNCATE TABLE software;');
out.push('TRUNCATE TABLE equipment;');
out.push('TRUNCATE TABLE equipment_type;');
out.push('TRUNCATE TABLE employee;');
out.push('TRUNCATE TABLE job_title;');
out.push('TRUNCATE TABLE department;');
out.push('SET FOREIGN_KEY_CHECKS = 1;');
out.push('');

// ---------------------------------------------------------------------
// department (6)
// ---------------------------------------------------------------------
const departments = ['IT', 'Finance', 'HR', 'Sales', 'Operations', 'Marketing'];
insertBatch(
  'department',
  ['department_id', 'department_name'],
  departments.map((department_name, i) => ({ department_id: i + 1, department_name })),
  'department (6)'
);

// ---------------------------------------------------------------------
// job_title (12)
// ---------------------------------------------------------------------
const jobTitles = [
  'Helpdesk Operator', 'IT Specialist', 'IT Analyst', 'IT Administrator',
  'Finance Manager', 'Accountant', 'HR Manager', 'HR Officer',
  'Sales Manager', 'Sales Executive', 'Operations Manager', 'Marketing Executive',
];
insertBatch(
  'job_title',
  ['job_title_id', 'title_name'],
  jobTitles.map((title_name, i) => ({ job_title_id: i + 1, title_name })),
  'job_title (12)'
);

// ---------------------------------------------------------------------
// employee (45). 1-13 are IT dept and become helpdesk_staff.
// 1-6 operators (job_title 1), 7-11 specialists (job_title 2),
// 12 analyst (job_title 3), 13 admin (job_title 4).
// ---------------------------------------------------------------------
const firstNames = ['James', 'Mary', 'John', 'Patricia', 'Robert', 'Jennifer', 'Michael', 'Linda',
  'William', 'Elizabeth', 'David', 'Barbara', 'Richard', 'Susan', 'Joseph', 'Jessica',
  'Thomas', 'Sarah', 'Charles', 'Karen', 'Daniel', 'Nancy', 'Matthew', 'Lisa', 'Anthony',
  'Betty', 'Mark', 'Margaret', 'Paul', 'Sandra', 'Steven', 'Ashley', 'Andrew', 'Kimberly',
  'Kenneth', 'Emily', 'George', 'Donna', 'Edward', 'Michelle', 'Brian', 'Carol', 'Ronald',
  'Amanda', 'Timothy'];
const lastNames = ['Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller', 'Davis',
  'Rodriguez', 'Martinez', 'Hernandez', 'Lopez', 'Gonzalez', 'Wilson', 'Anderson', 'Thomas',
  'Taylor', 'Moore', 'Jackson', 'Martin', 'Lee', 'Perez', 'Thompson', 'White', 'Harris',
  'Sanchez', 'Clark', 'Ramirez', 'Lewis', 'Robinson', 'Walker', 'Young', 'Allen', 'King',
  'Wright', 'Scott', 'Torres', 'Nguyen', 'Hill', 'Flores', 'Green', 'Adams', 'Nelson',
  'Baker', 'Hall'];

const EMPLOYEE_COUNT = 45;
const IT_STAFF_COUNT = 13;
// department/job_title plan for the 32 non-IT employees, cycling depts 2-6
const nonItPlan = [];
for (let i = 0; i < EMPLOYEE_COUNT - IT_STAFF_COUNT; i++) {
  const deptId = 2 + (i % 5); // Finance..Marketing
  const jobTitleByDept = { 2: [5, 6], 3: [7, 8], 4: [9, 10], 5: [11, 11], 6: [12, 12] };
  const options = jobTitleByDept[deptId];
  nonItPlan.push({ department_id: deptId, job_title_id: options[i % options.length] });
}

const employees = [];
for (let i = 1; i <= EMPLOYEE_COUNT; i++) {
  const first_name = firstNames[(i - 1) % firstNames.length];
  const last_name = lastNames[(i - 1 + Math.floor((i - 1) / firstNames.length)) % lastNames.length];
  let department_id, job_title_id;
  if (i <= 6) { department_id = 1; job_title_id = 1; }
  else if (i <= 11) { department_id = 1; job_title_id = 2; }
  else if (i === 12) { department_id = 1; job_title_id = 3; }
  else if (i === 13) { department_id = 1; job_title_id = 4; }
  else {
    const plan = nonItPlan[i - IT_STAFF_COUNT - 1];
    department_id = plan.department_id;
    job_title_id = plan.job_title_id;
  }
  employees.push({
    employee_id: i,
    first_name,
    last_name,
    email: `${first_name.toLowerCase()}.${last_name.toLowerCase()}${i}@manzaneque.co.uk`,
    phone_extension: String(randInt(1000, 9999)),
    department_id,
    job_title_id,
    is_active: 1,
  });
}
insertBatch(
  'employee',
  ['employee_id', 'first_name', 'last_name', 'email', 'phone_extension', 'department_id', 'job_title_id', 'is_active'],
  employees,
  'employee (45) — 1-13 are IT department and double as helpdesk_staff'
);

// ---------------------------------------------------------------------
// equipment_type (8)
// ---------------------------------------------------------------------
const equipmentTypes = ['Laptop', 'Desktop', 'Monitor', 'Printer', 'Phone', 'Tablet', 'Router', 'Scanner'];
insertBatch(
  'equipment_type',
  ['equipment_type_id', 'type_name'],
  equipmentTypes.map((type_name, i) => ({ equipment_type_id: i + 1, type_name })),
  'equipment_type (8)'
);

// ---------------------------------------------------------------------
// equipment (70). ~12 unassigned (stock/spares).
// ---------------------------------------------------------------------
const makesByType = {
  1: ['Dell', 'Lenovo', 'HP'], 2: ['Dell', 'HP', 'Apple'], 3: ['Dell', 'LG', 'Samsung'],
  4: ['HP', 'Canon', 'Brother'], 5: ['Apple', 'Samsung', 'Google'], 6: ['Apple', 'Samsung'],
  7: ['Cisco', 'Netgear', 'TP-Link'], 8: ['Canon', 'Epson'],
};
const EQUIPMENT_COUNT = 70;
const equipment = [];
for (let i = 1; i <= EQUIPMENT_COUNT; i++) {
  const equipment_type_id = ((i - 1) % 8) + 1;
  const make = pick(makesByType[equipment_type_id]);
  const unassigned = i % 6 === 0; // 11-12 of 70 left unassigned
  const assigned_employee_id = unassigned ? null : (((i - 1) % EMPLOYEE_COUNT) + 1);
  const purchaseDaysAgo = randInt(60, 1400);
  const purchase_date = new Date(Date.UTC(2026, 7, 20));
  purchase_date.setUTCDate(purchase_date.getUTCDate() - purchaseDaysAgo);
  equipment.push({
    equipment_id: i,
    serial_number: `MZQ-${String(equipment_type_id).padStart(2, '0')}-${String(i).padStart(4, '0')}`,
    equipment_type_id,
    make,
    model: `${make} ${equipmentTypes[equipment_type_id - 1]} ${2020 + (i % 6)}`,
    purchase_date: purchase_date.toISOString().slice(0, 10),
    assigned_employee_id,
    is_retired: chance(0.04) ? 1 : 0,
  });
}
insertBatch(
  'equipment',
  ['equipment_id', 'serial_number', 'equipment_type_id', 'make', 'model', 'purchase_date', 'assigned_employee_id', 'is_retired'],
  equipment,
  'equipment (70) — every 6th item left unassigned (stock/spares)'
);

// ---------------------------------------------------------------------
// software (15)
// ---------------------------------------------------------------------
const software = [
  ['Windows 11 Pro', 'Microsoft'], ['Microsoft 365', 'Microsoft'], ['Adobe Acrobat DC', 'Adobe'],
  ['Adobe Photoshop', 'Adobe'], ['AutoCAD', 'Autodesk'], ['Visual Studio Code', 'Microsoft'],
  ['SQL Server Standard', 'Microsoft'], ['Zoom', 'Zoom Video Communications'], ['Slack', 'Salesforce'],
  ['CrowdStrike Falcon', 'CrowdStrike'], ['VPN Client', 'Cisco'], ['Salesforce CRM', 'Salesforce'],
  ['SAP ERP', 'SAP'], ['Google Chrome Enterprise', 'Google'], ['Veeam Backup Agent', 'Veeam'],
];
insertBatch(
  'software',
  ['software_id', 'software_name', 'vendor'],
  software.map(([software_name, vendor], i) => ({ software_id: i + 1, software_name, vendor })),
  'software (15)'
);

// ---------------------------------------------------------------------
// software_licence (90). Mix of valid/expired; some equipment gets none
// (the "one missing" case is any equipment absent from this list — no
// special row needed, it falls out of the 70/~55-covered split below).
// ---------------------------------------------------------------------
const LICENCE_COUNT = 90;
const licences = [];
const licencedEquipmentIds = equipment
  .filter((e) => e.equipment_id % 9 !== 0) // ~8 equipment items get zero licences
  .map((e) => e.equipment_id);
for (let i = 1; i <= LICENCE_COUNT; i++) {
  const equipment_id = licencedEquipmentIds[(i - 1) % licencedEquipmentIds.length];
  const software_id = ((i - 1) % 15) + 1;
  const startDaysAgo = randInt(200, 900);
  const start = new Date(Date.UTC(2026, 7, 20));
  start.setUTCDate(start.getUTCDate() - startDaysAgo);
  const isExpired = i % 5 === 0; // 18 of 90 expired
  const durationDays = isExpired ? randInt(60, startDaysAgo - 5) : randInt(startDaysAgo + 30, startDaysAgo + 900);
  const end = new Date(start);
  end.setUTCDate(end.getUTCDate() + durationDays);
  licences.push({
    licence_id: i,
    equipment_id,
    software_id,
    licence_key: `LIC-${String(software_id).padStart(2, '0')}-${String(i).padStart(5, '0')}`,
    licence_start_date: start.toISOString().slice(0, 10),
    licence_end_date: end.toISOString().slice(0, 10),
  });
}
insertBatch(
  'software_licence',
  ['licence_id', 'equipment_id', 'software_id', 'licence_key', 'licence_start_date', 'licence_end_date'],
  licences,
  'software_licence (90) — ~1 in 5 expired, ~8 equipment items covered by none at all'
);

// ---------------------------------------------------------------------
// problem_type (22) — 3 levels. IDs fixed and referenced later.
// ---------------------------------------------------------------------
const problemTypes = [
  { id: 1, name: 'Hardware', parent: null },
  { id: 2, name: 'Software', parent: null },
  { id: 3, name: 'Network', parent: null },
  { id: 4, name: 'Account & Access', parent: null },
  { id: 5, name: 'Peripherals', parent: null },

  { id: 6, name: 'Laptop Issues', parent: 1 },
  { id: 7, name: 'Desktop Issues', parent: 1 },
  { id: 8, name: 'Printer Issues', parent: 1 },
  { id: 9, name: 'Application Issues', parent: 2 },
  { id: 10, name: 'Operating System Issues', parent: 2 },
  { id: 11, name: 'Licensing Issues', parent: 2 },
  { id: 12, name: 'Connectivity Issues', parent: 3 },
  { id: 13, name: 'VPN Issues', parent: 3 },
  { id: 14, name: 'Password Issues', parent: 4 },
  { id: 15, name: 'Permissions Issues', parent: 4 },
  { id: 16, name: 'Monitor Issues', parent: 5 },
  { id: 17, name: 'Input Device Issues', parent: 5 },

  { id: 18, name: 'Battery Failure', parent: 6 },
  { id: 19, name: 'Screen Damage', parent: 6 },      // no direct specialist — 1-level fallback to 6
  { id: 20, name: 'Office Application Crash', parent: 9 },
  { id: 21, name: 'WiFi Drop', parent: 12 },
  { id: 22, name: 'Account Locked', parent: 14 },    // no direct or parent specialist — 2-level fallback to 4
];
insertBatch(
  'problem_type',
  ['problem_type_id', 'type_name', 'parent_type_id'],
  problemTypes.map((t) => ({ problem_type_id: t.id, type_name: t.name, parent_type_id: t.parent })),
  'problem_type (22) — 3 levels; ids 19 and 22 are the deliberate fallback branches'
);

// ---------------------------------------------------------------------
// helpdesk_staff (13: 6 operators, 5 specialists, 1 analyst, 1 admin —
// the admin seat is required to exercise the Admin screen/role and was
// not itemised in ARCHITECTURE.md §3.7's volume list; see PROGRESS.md).
// bcrypt hash below is bcrypt('Password123!', cost 12) — same password
// for all seed accounts (username differs per role), documented in
// README as test credentials.
// ---------------------------------------------------------------------
const SEED_PASSWORD_HASH = '$2b$12$NufZZATc8zBw4C96hah2q.ZrD11A6Hoj1SEZam7Vpgg6yoKTseBpS';
const staffPlan = [
  { staff_id: 1, employee_id: 1, username: 'operator1', staff_role: 'OPERATOR' },
  { staff_id: 2, employee_id: 2, username: 'operator2', staff_role: 'OPERATOR' },
  { staff_id: 3, employee_id: 3, username: 'operator3', staff_role: 'OPERATOR' },
  { staff_id: 4, employee_id: 4, username: 'operator4', staff_role: 'OPERATOR' },
  { staff_id: 5, employee_id: 5, username: 'operator5', staff_role: 'OPERATOR' },
  { staff_id: 6, employee_id: 6, username: 'operator6', staff_role: 'OPERATOR' },
  { staff_id: 7, employee_id: 7, username: 'specialist1', staff_role: 'SPECIALIST' },
  { staff_id: 8, employee_id: 8, username: 'specialist2', staff_role: 'SPECIALIST' },
  { staff_id: 9, employee_id: 9, username: 'specialist3', staff_role: 'SPECIALIST' },
  { staff_id: 10, employee_id: 10, username: 'specialist4', staff_role: 'SPECIALIST' },
  { staff_id: 11, employee_id: 11, username: 'specialist5', staff_role: 'SPECIALIST' },
  { staff_id: 12, employee_id: 12, username: 'analyst1', staff_role: 'ANALYST' },
  { staff_id: 13, employee_id: 13, username: 'admin1', staff_role: 'ADMIN' },
];
insertBatch(
  'helpdesk_staff',
  ['staff_id', 'employee_id', 'username', 'password_hash', 'staff_role', 'is_active'],
  staffPlan.map((s) => ({ ...s, password_hash: SEED_PASSWORD_HASH, is_active: 1 })),
  'helpdesk_staff (13) — all seed accounts use password "Password123!" (see README)'
);

// ---------------------------------------------------------------------
// specialist_expertise — overlapping coverage, two deliberate gaps
// (types 19 and 22 have no direct specialist).
// ---------------------------------------------------------------------
const expertise = [
  // S1 (staff 7) — hardware generalist
  { staff_id: 7, problem_type_id: 1 }, { staff_id: 7, problem_type_id: 6 }, { staff_id: 7, problem_type_id: 18 },
  // S2 (staff 8) — desktop/printer, overlaps S1 on Laptop Issues (6)
  { staff_id: 8, problem_type_id: 7 }, { staff_id: 8, problem_type_id: 8 }, { staff_id: 8, problem_type_id: 6 },
  // S3 (staff 9) — software
  { staff_id: 9, problem_type_id: 2 }, { staff_id: 9, problem_type_id: 9 }, { staff_id: 9, problem_type_id: 20 }, { staff_id: 9, problem_type_id: 10 },
  // S4 (staff 10) — network/VPN, overlaps S3 on Licensing Issues (11)
  { staff_id: 10, problem_type_id: 3 }, { staff_id: 10, problem_type_id: 12 }, { staff_id: 10, problem_type_id: 13 }, { staff_id: 10, problem_type_id: 11 },
  { staff_id: 9, problem_type_id: 11 },
  // S5 (staff 11) — account/peripherals; note NOT type 14 (Password Issues) or 22 (Account Locked)
  { staff_id: 11, problem_type_id: 4 }, { staff_id: 11, problem_type_id: 15 }, { staff_id: 11, problem_type_id: 5 },
  { staff_id: 11, problem_type_id: 16 }, { staff_id: 11, problem_type_id: 17 },
];
insertBatch(
  'specialist_expertise',
  ['staff_id', 'problem_type_id'],
  expertise,
  'specialist_expertise — overlaps on types 6 (Laptop Issues: staff 7+8) and 11 (Licensing Issues: staff 9+10)'
);

// ---------------------------------------------------------------------
// Mirror of fn_find_specialist + sp_assign_least_loaded, in JS, so the
// generator can pick internally-consistent assignments (and so Phase 3
// checkpoint output has a known-correct answer to check the real SQL
// routines against).
// ---------------------------------------------------------------------
const typeById = Object.fromEntries(problemTypes.map((t) => [t.id, t]));
const expertiseByType = {};
for (const e of expertise) {
  (expertiseByType[e.problem_type_id] = expertiseByType[e.problem_type_id] || []).push(e.staff_id);
}
function findSpecialistTypeId(problemTypeId) {
  let cur = typeById[problemTypeId];
  while (cur) {
    if (expertiseByType[cur.id] && expertiseByType[cur.id].length > 0) return cur.id;
    cur = cur.parent ? typeById[cur.parent] : null;
  }
  return null;
}
// running open-load tracker used only to make seed assignment plausible
const openLoad = {}; // staff_id -> count
const lastAssignedAt = {}; // staff_id -> ms timestamp
function assignLeastLoaded(problemTypeId, atTime) {
  const resolvedTypeId = findSpecialistTypeId(problemTypeId);
  if (resolvedTypeId === null) return null;
  const candidates = expertiseByType[resolvedTypeId];
  let best = null;
  for (const staffId of candidates) {
    const load = openLoad[staffId] || 0;
    const last = lastAssignedAt[staffId] || 0;
    if (best === null || load < best.load || (load === best.load && last < best.last)) {
      best = { staffId, load, last };
    }
  }
  lastAssignedAt[best.staffId] = atTime;
  return best.staffId;
}

// ---------------------------------------------------------------------
// problem (~250) over the 6 months to 2026-08-20, plus call_log (~400).
// ---------------------------------------------------------------------
const PROBLEM_COUNT = 250;
const PERIOD_START = Date.UTC(2026, 1, 20); // 2026-02-20
const PERIOD_END = Date.UTC(2026, 7, 20);   // 2026-08-20 (today)
const priorities = ['LOW', 'LOW', 'MEDIUM', 'MEDIUM', 'MEDIUM', 'HIGH', 'HIGH', 'CRITICAL'];
const leafHeavyTypeIds = [18, 19, 20, 21, 22, 7, 8, 10, 13, 15, 16, 17];
const allAssignableTypeIds = problemTypes.map((t) => t.id);

const problems = [];
const callLogs = [];
let callLogIdSeq = 1;

for (let pid = 1; pid <= PROBLEM_COUNT; pid++) {
  const loggedAtMs = PERIOD_START + Math.floor(rnd() * (PERIOD_END - PERIOD_START - 86400000));
  const logged_at = new Date(loggedAtMs);

  const caller_employee_id = randInt(1, EMPLOYEE_COUNT);
  const equipment_id = randInt(1, EQUIPMENT_COUNT);
  const problem_type_id = chance(0.65) ? pick(leafHeavyTypeIds) : pick(allAssignableTypeIds.filter((id) => id > 5));
  const logged_by_staff_id = randInt(1, 6); // an operator
  const priority = pick(priorities);

  // outcome distribution: 70% CLOSED, 15% RESOLVED, 15% still open (OPEN/ASSIGNED/IN_PROGRESS)
  const roll = rnd();
  let status;
  if (roll < 0.70) status = 'CLOSED';
  else if (roll < 0.85) status = 'RESOLVED';
  else status = pick(['OPEN', 'OPEN', 'ASSIGNED', 'IN_PROGRESS']);

  let assigned_staff_id = null;
  if (status !== 'OPEN') {
    assigned_staff_id = assignLeastLoaded(problem_type_id, loggedAtMs);
  }

  let resolved_at = null, resolution_notes = null, minutes_to_resolve = null;
  if (status === 'RESOLVED' || status === 'CLOSED') {
    const priorityCapMinutes = { CRITICAL: 240, HIGH: 720, MEDIUM: 2880, LOW: 5760 }[priority];
    const durationMin = randInt(15, priorityCapMinutes);
    const resolvedMs = Math.min(loggedAtMs + durationMin * 60000, PERIOD_END - 3600000);
    resolved_at = new Date(Math.max(resolvedMs, loggedAtMs + 60000));
    minutes_to_resolve = Math.round((resolved_at.getTime() - loggedAtMs) / 60000);
    resolution_notes = `Resolved by reproducing the issue and applying the standard fix for ${typeById[problem_type_id].name.toLowerCase()}.`;
    // problem stays open in the tracker only up to its resolution — decrement load
    if (assigned_staff_id) openLoad[assigned_staff_id] = Math.max(0, (openLoad[assigned_staff_id] || 0));
  } else if (assigned_staff_id) {
    openLoad[assigned_staff_id] = (openLoad[assigned_staff_id] || 0) + 1;
  }

  problems.push({
    problem_id: pid, caller_employee_id, equipment_id, problem_type_id,
    status, priority, assigned_staff_id, logged_by_staff_id, logged_at,
    resolved_at, resolution_notes, minutes_to_resolve,
  });

  callLogs.push({
    call_log_id: callLogIdSeq++, problem_id: pid, staff_id: logged_by_staff_id,
    call_type: 'INITIAL',
    notes: `Caller reported: ${typeById[problem_type_id].name.toLowerCase()} on equipment logged at intake.`,
    logged_at,
  });

  // budgeted to land total call_log rows near the ~400 target in §3.7
  const generalFollowUp = chance(0.2);
  if (generalFollowUp) {
    const followUpStaff = assigned_staff_id || logged_by_staff_id;
    const offsetMs = Math.floor((rnd() * (resolved_at ? resolved_at.getTime() - loggedAtMs : 86400000 * 2)));
    callLogs.push({
      call_log_id: callLogIdSeq++, problem_id: pid, staff_id: followUpStaff,
      call_type: 'FOLLOW_UP',
      notes: 'Follow-up: gathered further diagnostic detail from the caller.',
      logged_at: new Date(loggedAtMs + offsetMs + 60000),
    });
  }
  if (resolved_at && assigned_staff_id && chance(0.65)) {
    callLogs.push({
      call_log_id: callLogIdSeq++, problem_id: pid, staff_id: assigned_staff_id,
      call_type: 'FOLLOW_UP',
      notes: `Resolved: ${resolution_notes}`,
      logged_at: resolved_at,
    });
  }
}

insertBatch(
  'problem',
  ['problem_id', 'caller_employee_id', 'equipment_id', 'problem_type_id', 'status', 'priority',
    'assigned_staff_id', 'logged_by_staff_id', 'logged_at', 'resolved_at', 'resolution_notes', 'minutes_to_resolve'],
  problems,
  `problem (${PROBLEM_COUNT}) over 2026-02-20..2026-08-20`
);

callLogs.sort((a, b) => a.call_log_id - b.call_log_id);
insertBatch(
  'call_log',
  ['call_log_id', 'problem_id', 'staff_id', 'call_type', 'notes', 'logged_at'],
  callLogs,
  `call_log (${callLogs.length})`
);

out.push('-- audit_log is intentionally left empty by seed data: it is trigger-populated');
out.push('-- (trg_problem_after_update) and INSERT does not fire an AFTER UPDATE trigger.');
out.push('-- Any status/type/assignment change made through the app from here on will');
out.push('-- start populating it.');
out.push('');
out.push(`-- Row counts: department=${departments.length}, job_title=${jobTitles.length}, employee=${employees.length},`);
out.push(`-- equipment_type=${equipmentTypes.length}, equipment=${equipment.length}, software=${software.length},`);
out.push(`-- software_licence=${licences.length}, problem_type=${problemTypes.length}, helpdesk_staff=${staffPlan.length},`);
out.push(`-- specialist_expertise=${expertise.length}, problem=${problems.length}, call_log=${callLogs.length}`);

const outPath = path.join(__dirname, '..', '07_seed.sql');
fs.writeFileSync(outPath, out.join('\n') + '\n', 'utf8');
console.log(`Wrote ${outPath}`);
console.log(`problem status breakdown: ${JSON.stringify(
  problems.reduce((acc, p) => { acc[p.status] = (acc[p.status] || 0) + 1; return acc; }, {})
)}`);
